C:/work/github/RV32-FullStack/ip_workspace/0_IF/0_PC/next_pc_mux.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/0_PC/pc_adder.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/0_PC/program_counter.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/1_adress_split/address_aligner.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/1_adress_split/cache_controller.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/1_adress_split/comparator.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/1_adress_split/icache_axi_adapter.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/1_adress_split/icache_data_array.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/1_adress_split/icache_unit.vhd
C:/work/github/RV32-FullStack/ip_workspace/0_IF/1_adress_split/tag_array.vhd
C:/work/github/RV32-FullStack/ip_workspace/1_ID/control_unit.vhd
C:/work/github/RV32-FullStack/ip_workspace/1_ID/csr_file.vhd
C:/work/github/RV32-FullStack/ip_workspace/1_ID/hazard_unit.vhd
C:/work/github/RV32-FullStack/ip_workspace/1_ID/imm_gen.vhd
C:/work/github/RV32-FullStack/ip_workspace/1_ID/register_file.vhd
C:/work/github/RV32-FullStack/ip_workspace/2_EX/alu.vhd
C:/work/github/RV32-FullStack/ip_workspace/2_EX/alu_control.vhd
C:/work/github/RV32-FullStack/ip_workspace/2_EX/bcu.vhd
C:/work/github/RV32-FullStack/ip_workspace/2_EX/forwarding_unit.vhd
C:/work/github/RV32-FullStack/ip_workspace/2_EX/trap_unit.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/axi_master.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/axi_slave_mem.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/cache_unit.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/dcache_controller.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/ddata_array.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/dtag_array.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/read_aligner.vhd
C:/work/github/RV32-FullStack/ip_workspace/3_Mem/write_strobe_gen.vhd
C:/work/github/RV32-FullStack/ip_workspace/4_WB/result_mux.vhd
C:/work/github/RV32-FullStack/ip_workspace/5_Platform/gpio_port.vhd
C:/work/github/RV32-FullStack/ip_workspace/5_Platform/i2c_master.vhd
C:/work/github/RV32-FullStack/ip_workspace/5_Platform/mmio_bridge.vhd
C:/work/github/RV32-FullStack/ip_workspace/5_Platform/pwm_gen.vhd
C:/work/github/RV32-FullStack/ip_workspace/5_Platform/rv32_ctrl_axi.vhd
C:/work/github/RV32-FullStack/ip_workspace/5_Platform/spi_master.vhd
C:/work/github/RV32-FullStack/ip_workspace/5_Platform/uart_lite.vhd
C:/work/github/RV32-FullStack/ip_workspace/6_NPU/npu_array.vhd
C:/work/github/RV32-FullStack/ip_workspace/6_NPU/npu_pe.vhd
C:/work/github/RV32-FullStack/ip_workspace/6_NPU/npu_top.vhd
C:/work/github/RV32-FullStack/ip_workspace/common/pipeline_reg.vhd
C:/work/github/RV32-FullStack/ip_workspace/rv32_core.vhd
C:/work/github/RV32-FullStack/ip_workspace/rv32_soc.vhd
C:/work/github/RV32-FullStack/verification/npu_soc_sim/rv32_soc_npu.vhd
