C:/work/github/RV32-FullStack/rtl/core/pc/next_pc_mux.vhd
C:/work/github/RV32-FullStack/rtl/core/pc/pc_adder.vhd
C:/work/github/RV32-FullStack/rtl/core/pc/program_counter.vhd
C:/work/github/RV32-FullStack/rtl/core/icache/address_aligner.vhd
C:/work/github/RV32-FullStack/rtl/core/icache/cache_controller.vhd
C:/work/github/RV32-FullStack/rtl/core/icache/comparator.vhd
C:/work/github/RV32-FullStack/rtl/core/icache/icache_axi_adapter.vhd
C:/work/github/RV32-FullStack/rtl/core/icache/icache_data_array.vhd
C:/work/github/RV32-FullStack/rtl/core/icache/tag_array.vhd
C:/work/github/RV32-FullStack/rtl/core/icache/icache_unit.vhd
C:/work/github/RV32-FullStack/rtl/core/id/control_unit.vhd
C:/work/github/RV32-FullStack/rtl/core/id/csr_file.vhd
C:/work/github/RV32-FullStack/rtl/core/id/hazard_unit.vhd
C:/work/github/RV32-FullStack/rtl/core/id/imm_gen.vhd
C:/work/github/RV32-FullStack/rtl/core/id/register_file.vhd
C:/work/github/RV32-FullStack/rtl/core/ex/alu.vhd
C:/work/github/RV32-FullStack/rtl/core/ex/alu_control.vhd
C:/work/github/RV32-FullStack/rtl/core/ex/bcu.vhd
C:/work/github/RV32-FullStack/rtl/core/ex/forwarding_unit.vhd
C:/work/github/RV32-FullStack/rtl/core/ex/trap_unit.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/axi_master.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/axi_slave_mem.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/dtag_array.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/ddata_array.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/dcache_controller.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/cache_unit.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/read_aligner.vhd
C:/work/github/RV32-FullStack/rtl/core/mem/write_strobe_gen.vhd
C:/work/github/RV32-FullStack/rtl/core/wb/result_mux.vhd
C:/work/github/RV32-FullStack/rtl/common/pipeline_reg.vhd
C:/work/github/RV32-FullStack/rtl/core/rv32_core.vhd
C:/work/github/RV32-FullStack/rtl/soc/rv32_shared.vhd
C:/work/github/RV32-FullStack/rtl/soc/rv32_dual.vhd
C:/work/github/RV32-FullStack/sim/multicore/tb_rv32_dual.vhd
